numpy

In [2]:
#numpy基本属性
import numpy as np
#列表转化为矩阵
array = np.array([[1,2,3],[2,3,4]])  
print(array)
print(array.ndim)
print(array.shape)
print(array.size)

[[1 2 3]
 [2 3 4]]
2
(2, 3)
6


In [7]:
#array的创建
array=np.array([1,2,3])
print(array)
array=np.arange(12).reshape((3,4))
print(array)
array=np.linspace(0,10,10).reshape((2,5))
print(array)
#指定数据类型
array=np.array([1,2,3],dtype=np.float)
print(array)
#创建特殊的矩阵
a=np.zeros((3,4))
print(a)
b=np.ones((2,2))
print(b)
c=np.empty((2,3))
print(c)

[1 2 3]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0.           1.11111111   2.22222222   3.33333333   4.44444444]
 [  5.55555556   6.66666667   7.77777778   8.88888889  10.        ]]
[ 1.  2.  3.]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 1.  1.]
 [ 1.  1.]]
[[  2.12199579e-314   6.36598737e-314   1.06099790e-313]
 [  1.48539705e-313   1.90979621e-313   2.33419537e-313]]


In [33]:
#numpy的基础运算
a=np.array([[1,2],[0,2]])
b=np.arange(4).reshape(2,2)
#矩阵的乘法
c=np.dot(a,b)
print(c)
d=a.dot(b)
print(d)

[[4 7]
 [4 6]]
[[4 7]
 [4 6]]


In [34]:
#寻找最大值、最小值
#寻找全局的最值
print(np.max(a))
#寻找每行每列的
print(np.max(a,axis=1))
#numpy最值的索引
print(np.argmin(a))    
print(np.argmax(a))   
#numpy的均值
print(np.mean(a))       
print(np.average(a))
print(a.mean())

2
[2 2]
2
1
1.25
1.25
1.25


In [36]:
#numpy的累加、累减
print(np.cumsum(a))
print(np.diff(a))
#numpy判断非零
print(np.nonzero(a))
#矩阵的排序 针对每行
print(np.sort(a))
#矩阵的转置
print(np.transpose(a))
print(a.T)
########针对特殊矩阵的转置
A = np.array([1,1,1])
print(A[np.newaxis,:])
print(A[:,np.newaxis])
#clip
print(np.clip(a,0,1))

[1 3 3 5]
[[1]
 [2]]
(array([0, 0, 1], dtype=int64), array([0, 1, 1], dtype=int64))
[[1 2]
 [0 2]]
[[1 0]
 [2 2]]
[[1 0]
 [2 2]]
[[1 1 1]]
[[1]
 [1]
 [1]]
[[1 1]
 [0 1]]


In [28]:
#numpy的索引
a=np.arange(12).reshape(3,4)
print(a)
print(a[1,1:3])
print(a.flatten())   
for item in a.flat:
    print(item)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[5 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
0
1
2
3
4
5
6
7
8
9
10
11


In [40]:
#numpy的合并
#上下合并
A = np.array([1,1,1])
B = np.array([2,2,2])      
print(np.vstack((A,B)))  
#左右合并
D = np.hstack((A,B))
print(D)
#合并多个
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
D = np.concatenate((A,B,B,A),axis=1)
print(D)

[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [42]:
#numpy的分割
A = np.arange(12).reshape((3, 4))
#纵向分割
print(np.split(A, 2, axis=1))
#横向分割
print(np.split(A, 3, axis=0))
#错误分割
#print(np.split(A, 3, axis=1))
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


In [44]:
#copy和deep copy
#copy
a = np.arange(4)
b = a
print(a)
print(b)
a[0] = 11
print(a)
print(b)
#deep copy
b = a.copy()  
print(a)
print(b)       
a[3] = 44
print(a)     
print(b)        

[0 1 2 3]
[0 1 2 3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2  3]
[11  1  2 44]
[11  1  2  3]
