1、数组续

In [2]:
#arange 返回的是数组
#arange(start, stop=None, step=1, dtype=None)
#产生一个在区间 [start, stop) 之间，以 step 为间隔的数组，如果只输入一个参数，则默认从 0 开始，并以这个值为结束
#由于存在精度问题，使用浮点数可能出现问题
from numpy import *
arange(1.5, 2.1, 0.3)
#注意其中包含了2.1

array([ 1.5,  1.8,  2.1])

In [ ]:
#linspace
#linspace(start, stop, N)
#产生 N 个等距分布在 [start, stop]间的元素组成的数组，包括 start, stop。

In [4]:
#logspace
#logspace(start, stop, N)
#产生 N 个对数等距分布的数组，默认以10为底：
logspace(0, 1, 5)

array([  1.        ,   1.77827941,   3.16227766,   5.62341325,  10.        ])

In [ ]:
#生成网格
x_ticks = linspace(-1, 1, 5)
y_ticks = linspace(-1, 1, 5)
x, y = meshgrid(x_ticks, y_ticks)
#或者
x, y = ogrid[-1:1:.5, -1:1:.5]
#Numpy 使用的是 start:end:step 的表示，结果不包括 end 的值
#为了包含 end 的值，我们可以使用这样的技巧：
x, y = ogrid[-1:1:5j, -1:1:5j]

In [6]:
#使用 r_ / c_ 来产生行向量或者列向量
print(r_[0:1:5j])
#产生列向量
c_[1:3:5j]

[ 0.    0.25  0.5   0.75  1.  ]


array([[ 1. ],
       [ 1.5],
       [ 2. ],
       [ 2.5],
       [ 3. ]])

In [8]:
#ones或者zeros
#ones(shape, dtype=float64)
#zeros(shape, dtype=float64)
#产生一个制定形状的全 0 或全 1 的数组，还可以制定数组类型
ones([2,3]) * 5

array([[ 5.,  5.,  5.],
       [ 5.,  5.,  5.]])

In [9]:
#empty(shape, dtype=float64, order='C')
#使用 empty 方法产生一个制定大小的数组（数组所指向的内存未被初始化，所以值随机），再用 fill 方法填充：
a = empty(2)
print(a)
a.fill(5)
a

[  1.17518756e+180   2.44524720e-154]


array([ 5.,  5.])

In [ ]:
#empty_like, ones_like, zeros_like
empty_like(a)
ones_like(a)
zeros_like(a)
产生一个跟 a 大小一样，类型一样的对应数组

In [ ]:
#identity
indentity(n, dtype=float64)
产生一个 n 乘 n 的单位矩阵

2、矩阵

In [10]:
#将 2 维数组转化为矩阵
a = array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
A = mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [11]:
#传入一个字符串来生成矩阵：
A = mat('1,2,4;2,5,3;7,8,9')
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [12]:
#利用分块创造新的矩阵：
a = array([[ 1, 2],
              [ 3, 4]])
b = array([[10,20], 
              [30,40]])
bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

In [13]:
#矩阵的逆
A.I

matrix([[-0.42857143, -0.28571429,  0.28571429],
        [-0.06122449,  0.3877551 , -0.10204082],
        [ 0.3877551 , -0.12244898, -0.02040816]])

3、向量化函数

In [14]:
#自定义sinc函数，不能作用于函数
import numpy as np
def sinc(x):
    if x == 0.0:
        return 1.0
    else:
        w = np.pi * x
        return np.sin(w) / w

In [15]:
#可以使用 numpy 的 vectorize 将函数 sinc 向量化，产生一个新的函数
vsinc = np.vectorize(sinc)
x = np.array([1,2,3])
vsinc(x)

array([  3.89817183e-17,  -3.89817183e-17,   3.89817183e-17])

4、非法值nan

In [ ]:
#只有 0/0 会得到 nan，非0值除以0会得到无穷
#nan 与任何数进行比较都是 False
#想要找出 nan 值需要使用 isnan

5、操作符

In [18]:
#=是逐元素比较的
#如果我们在条件中要判断两个数组是否一样时，不能直接使用
a = np.array([[1,2,3,4],
              [2,3,4,5]])
b = np.array([[1,2,5,4],
              [1,3,4,5]])
print(a == b)
#可以使用
print(all(a==b))
#对于浮点数，由于存在精度问题，使用函数 allclose 会更好：
print(allclose(a,b))

[[ True  True False  True]
 [False  True  True  True]]
False
False


6、ufunc对象

In [21]:
#针对ufunc对象有以下方法：
#reduce 方法  op.reduce(a)
#将op沿着某个轴应用，使得数组 a 的维数降低一维
a = np.array([1,2,3,4])
print(add.reduce(a))
#默认第一维进行运算
#但可以指定维度
a = np.array([[1,2,3],[4,5,6]])
np.add.reduce(a, 1)

10


array([ 6, 15])

In [22]:
#accumulate 方法 op.accumulate(a)
#accumulate 可以看成保存 reduce 每一步的结果所形成的数组。
a = np.array([1,2,3,4])
np.add.accumulate(a)

array([ 1,  3,  6, 10], dtype=int32)

In [23]:
#outer 方法 op.outer(a, b)
#对于 a 中每个元素，将 op 运用到它和 b 的每一个元素上所得到的结果：
a = np.array([0,1])
b = np.array([1,2,3])
print(np.add.outer(a, b))
#注意有顺序的区别：
print(np.add.outer(b, a))

[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]


7、choose函数实现条件筛选

8、数组广播机制

In [25]:
a = np.array([[ 0, 0, 0],
              [10,10,10],
              [20,20,20],
              [30,30,30]])
b = np.array([0,1,2])
a + b
#将 b 扩展得到相同的形状

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [26]:
#对于 Numpy 来说，维度匹配当且仅当：维度相同、有一个的维度是1
#匹配会从最后一维开始进行，直到某一个的维度全部匹配为止
#即是，从最后一维开始匹配，然后遇1则变为较大的那个维数
a = np.array([0,10,20,30])
a.shape = 4,1
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

9、数组读写

In [ ]:
#文本形式
loadtxt 读数组
savetxt 写数组

#Numpy 二进制格式
数组可以储存成二进制格式，单个的数组保存为 .npy 格式，多个数组保存为多个.npy文件组成的 .npz 格式，每个 .npy 文件包含一个数组。
与文本格式不同，二进制格式保存了数组的 shape, dtype 信息，以便完全重构出保存的数组。

#保存的方法：
save(file, arr) 保存单个数组，.npy 格式
savez(file, *args, **kwds) 保存多个数组，无压缩的 .npz 格式
savez_compressed(file, *args, **kwds) 保存多个数组，有压缩的 .npz 格式

#读取的方法：
load(file, mmap_mode=None) 对于 .npy，返回保存的数组，对于 .npz，返回一个名称-数组对组成的字典。

10、结构化数组

In [27]:
#自定义结构类型，然后初始化结构化数组
my_dtype = np.dtype([('mass', 'float32'), ('vol', 'float32')])
my_data = np.array([(1,1), (1,2), (2,1), (1,3)], my_dtype)
my_data

array([( 1.,  1.), ( 1.,  2.), ( 2.,  1.), ( 1.,  3.)],
      dtype=[('mass', '<f4'), ('vol', '<f4')])

In [ ]:
#嵌套类型
particle_dtype = np.dtype([('position', [('x', 'float'), 
                                         ('y', 'float')]),
                           ('mass', 'float')
                          ])

11、记录数组

In [29]:
#记录数组（record array）与结构数组类似
#记录数组的运行效率要比结构化数组要慢一些
partical_dtype = np.dtype([('mass', 'float'), 
                           ('velocity', 'float')])
#生成记录数组要使用 numpy.rec 里的 fromrecords 方法
from numpy import rec
particals_rec = rec.fromrecords([(1,1), (1,2), (2,1), (1,3)],dtype = partical_dtype)
particals_rec

rec.array([( 1.,  1.), ( 1.,  2.), ( 2.,  1.), ( 1.,  3.)], 
          dtype=[('mass', '<f8'), ('velocity', '<f8')])